name: H5P Version Action
description: Outputs H5P library's version number

author: Sindre Bøyum

branding:
  color: blue
  icon: aperture

inputs:
  working-directory: # change this
    required: false
    description: The directory where library.json is found
    default: "."

outputs:
  version:
    description: An object with the fields `major`, `minor` and `patch`

  version-formatted:
    description: A string on the form `{majorVersion}.{minorVersion}.{patchVersion}`

runs:
  using: node16
  main: dist/index.js
